schema:
  - ./schema/schema.gql
extensions:
  endpoints:
    local:
      url: "http://localhost:3001/"
    authenticated local:
      url: "http://localhost:3001/"
      headers:
        authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjkxODUyMDk3LCJzdWIiOiI3OTMwODg2ZC0zNzYwLTRlNzUtYWNhOC03NWJjMzNlMTZlYjYiLCJlbWFpbCI6InRlc3RnQG1haWxhLm1nIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2OTE4NDg0OTd9XSwic2Vzc2lvbl9pZCI6ImY1NTBlZDVjLWFiOGQtNGJkNy04MmY5LTZmZTU5NjRlZDY1MSJ9.rNu3BT-5sSvpKMFKHcv-o853DEar3pc_Sk61jHQ4zYk"