schema:
  - ./schema/schema.gql
extensions:
  endpoints:
    local:
      url: "http://localhost:3001/"
    authenticated local:
      url: "http://localhost:3001/"
      headers:
        authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjkwNjQzNjgxLCJzdWIiOiI2NmY5MjNjYy0wNTgxLTRhZTAtYWQ3MC05OGIyNzQzOGQ2MjkiLCJlbWFpbCI6ImZpbmFyaXRyYW5kcmlhbmlhaW5hQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnt9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNjkwNjQwMDgxfV0sInNlc3Npb25faWQiOiI1ZjkzN2Y5Mi00YTA0LTRmZWYtYmIwOC0wZjZhYzRhNzcyYWQifQ.R0KWCMibSXGbwvpLzsbUtnbijuAZxVMGwPtnWm2XE5I"
