import process from "process";

export const WORKER_HOST = process.env.WORKER_HOST || 'localhost';
export const WORKER_PORT = Number(process.env.WORKER_PORT) || 6379;
export const WORKER_PASS = process.env.WORKER_PASS || 'eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81';

export enum TRANSFORMER_QUEUE {
    NAME = 'TRANSFORMER_QUEUE',
    STRIPE_SEND = "STRIPE_SEND",
    TRANSFORMER_CREATE_PRODUCT = "TRANSFORMER_CREATE_PRODUCT",
    USER_LIKE_PRODUCT_ACTION = "USER_LIKE_PRODUCT_ACTION",
    PROFILE_CREATED_ACTION = "PROFILE_CREATED_ACTION",
}